=== zakaio/atala-prism-schema/json_schema/meta/prism-credentials.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://prism.proofspace.id/prism-credential-schema",
  "$comment": "TODO: get domain name in cardano ecosystem",
  "title": "PRISM Credential Schema Definition",
  "type": "object",
  "properties": {
     "name": { 
	     "type": "string",
	     "maxLength": 255,
	     "minLength": 1,
	     "title": "schema name",
	     "description": "schema name (arbitraty string)"
     },
     "version": { "type":  "string" },
     "description": { "type": "string" },
     "id": { 
        "type": "string",
	"$comment": "TODO: shoult be URI",
	"description": "Unique schema id. Publishing tool should check uniquiness of id during submtting schema to blockchain"
     },
     "author": { 
	 "$ref":  "#/$defs/did" 
     },
     "trustRegistry": {
	   "$ref": "#/$defs/trustRegistry"
     },
     "properties": {
	 "type" : "object",
	 "additionalProperties" : { "$ref": "#/$defs/field" }
     },
     "uniquiness": { "type": "array", "items": { "type":"string" }  },
     "comment": { "type": "string" }
  },
  "required": [ "name", "version", "id", "author", "trustRegistry", "properties" ],
  "$defs": {
     "trustRegistry": {
	 "title": "definition of trust registry",
         "type": "object",
	 "oneOf": [
	    { 
	      "type": "object",
	      "properties": {
		  "type": { "const" : "issuer"} ,
		  "issuer": { "$ref": "#/$defs/did" }
	       }
	    },
	    { 
	      "type": "object",
	      "properties": {
		  "type": { "const": "token-registry"} ,
		  "token": { "type": "string" }
	      }
	    },
	    { 
	      "type": "object",
	      "properties": {
		  "type": { "const" : "permissionless"} 
	       }
	    }
	 ]
     },
     "field": {
        "title": "credential field",
	"allOf": [
	  { "type": "object",
            "properties": {
	      "title": { "type": "string" },
	      "fieldName": {"type": "string"},
	      "description": { "type": "string" },
	      "contextUri": { "type": "string" },
	      "optional": { "type": "boolean" },
	      "disclosable": { "type": "boolean" },
	      "comparable": { "type": "boolean" },
	      "indexable": { "type": "boolean" },
	      "unique": { "type": "boolean" }
	     }
	  },
	  {
	   "oneOf" : [
             {
              "type" : "object",
              "properties" : {
		 "type" : { "const": "string" },
		 "pattern" : { "type": "string", 
			       "$comment": "TODO: define format for regexpr"
		             },
		 "minLength": {  "type" : "integer" },   	    
		 "maxLength": {  "type" : "integer" },
		 "multiline": {  "type" : "boolean",
			         "description": "should fields be displayed as multiline"
		              },
	         "keyboardHint": {  "type" : "string",
			       "$comment": "TODO: define enum"
		 }
	       }
	     },
	     {
              "type" : "object",
              "properties" : {
		 "type" : { "const": "integer" },
		 "minimum": { "type": "integer"},
		 "maximum": { "type": "integer"}
	      }
	     },
	     {
              "type" : "object",
              "properties" : {
		 "type" : { "const": "number" }
	      }
	     },
	     {
              "type" : "object",
              "properties" : {
		 "type" : { "const": "decimal" }
	      }
	     },
	     {
              "type" : "object",
              "properties" : {
		 "type" : { "const": "boolean" }
	      }
	     },
	     {
               "type" : "object",
               "properties" : {
		  "type" : { "const": "timestamp" },
		  "timeOf" : { "$ref": "#/$defs/timestampEvent" }
	       },
	       "$comment" : "string - RFC3339 timestamp"
	     },
	     {
               "type" : "object",
               "properties" : {
		  "type" : { "const": "date" }
	       },
	       "$comment" : "string - ISO8601 date"
	     },
	     {
               "type" : "object",
               "properties" : {
		  "type" : { "const": "enum" },
		  "values" : {  "type": "array", "items": { "type": "string" } }
	       }
	     },
	     {
               "type" : "object",
               "properties" : {
		  "type" : { "const": "array" },
		  "items" : { "$ref": "#/$defs/field"  }
	       }
	     }
           ]	   
	 } 
       ]
     },
     "did": {
	"type": "string",
	"title": "did",
	"description": "decentralizes identifier (did) as specified in 'https://www.w3.org/TR/did-core' "
     },
     "timestampEvent": {
	"title": "Event associated with timestamp",     
	"desription": "if present, denote a special value of timestamp field",
	"type": "string",
	"enum": [ "issuing", "expiration" ]
     }
  }  
}

=== zakaio/atala-prism-schema/examples/schemas/pos/proof-of-payment.json
{
  "name": "Link between DID and Address",
  "version": "1.0",
  "id": "https://proofspace.id/prism-schemas/did-address-link",
  "description": "proof, that address make payment",
  "author": "ProofSpace",
  "trustRegistry": {
    "type": "issuer",
    "did": "did:TODO:some-example-did"
  },
  "properties": {
    "address": { "type": "string" },
    "amount": { "type": "decimal" },
    "code": { "type": "string" },
    "transactionId": { "type": "string" },
    "transactionIdx": { "type": "integer" },
    "tag": { "type": "string" },
    "paymentTime": { "type": "timestamp" },
    "issueTime": {
      "type": "timestamp",
      "timeOf": "issuing"
    }
  }
}

=== zakaio/atala-prism-schema/examples/schemas/pos/AtalaPrismPioneerCeritificationCourse.json
{
 "name": "Atala Prism Pioneer Completition Certificate",
 "description": "subj",
 "id": "https://credentials.cardano/completition-certificate",
 "version": "0.0.1",
 "author": "did:prism:<need-to-define>",
 "trustRegistry": {
	 "type": "issuer"
 },
 "properties": {
    "Course Name": { "type": "string" },
    "Course Version": { "type": "string" },
    "Full Name": { "type": "string" },
    "Email": { "type": "string" },
    "Date of Completition": { "type": "date" }
 }
}

=== zakaio/atala-prism-schema/examples/schemas/pos/PersonName.json
{
  "name": "PersonName",
  "description": "Person name (currently - minimal sub-schema)",
  "id": "https://schema.org/Person",
  "version": "0.0.1",
  "author": "did:email:ruslan@shevchenko.kiev.ua",
  "trustRegistry": {
    "type": "permissionless"
  },
  "properties": {
    "givenName": { "type": "string" },
    "familyName": { "type": "string" }
  }
}

=== zakaio/atala-prism-schema/examples/schemas/pos/locked-amount.json
{
 "name": "Locked Amount",
 "version": "1.0",
 "id":"https://proofspace.id/prism-schemas/token-credentials/locked-amound",
 "description":  "proof, that address linked to did have some amount locked in smart-contract",
 "author": "ProofSpace",
 "trustRegistry": {
	 "type" : "permissionless"
 },
 "properties": {
    "tag": { "type": "string" },
    "address": { "type": "string"},
    "lockAmount": { "type": "decimal" },
    "lockTime": { 
	 "type": "timestamp",
	 "description": "time, until lock is valid. After expiring this time, owner can return unspend amount back",
	 "timeOf" : "expiration"
    },
    "lockInput": { "type": "string" },
    "tokenName": {  "type": "string" },
    "transactionId": { "type" : "string" },
    "unlockKey": { 
	    "type" : "string",
	    "title" : "Unlock Key",
	    "description" : "If this value is not 'none', than entity who receive this credential can unlock amount and receive token"
       },
    "issuedDate": {
	 "type": "timestamp",
	 "description": "When this credential was issued",
	 "timeOf" : "issuing"
    }
 }
}

=== zakaio/atala-prism-schema/examples/schemas/pos/link-did-to-address.json
{
 "name": "AddressDID",
 "version": "1.0",
 "id":"https://proofspace.id/prism-schemas/token-credentials/did-address-link",
 "description": "Link between DID and Address",
 "author" : "ProofSpace",
 "trustRegistry": {
	 "type": "issuer",
	 "comment": "TODO: stricter need for did here ?"
  },
 "properties": {
    "address": { "type": "string"},
    "transactionId": { "type" : "string" },
    "tag": { "type": "string" },
    "issuedDate": { 
	    "type" : "timestamp",
	    "title": "Credential Issued Date"
    }
 }
}
